<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request.proto

namespace GPBMetadata;

class Request
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\User::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a660a0d726571756573742e70726f746f1211506870576f726c642e4d65" .
            "737361676573223a0a075265717565737412270a04757365721801200128" .
            "0b32172e506870576f726c642e4d657373616765732e5573657248004206" .
            "0a0464617461620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

