<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

namespace GPBMetadata;

class User
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a580a0a757365722e70726f746f1211506870576f726c642e4d65737361" .
            "676573222f0a0455736572120c0a046e616d65180120012809120a0a0269" .
            "64180220012805120d0a05656d61696c180320012809620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

