<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request.proto

namespace PhpWorld\Messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>PhpWorld.Messages.Request</code>
 */
class Request extends \Google\Protobuf\Internal\Message
{
    protected $data;

    public function __construct() {
        \GPBMetadata\Request::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.PhpWorld.Messages.User user = 1;</code>
     * @return \PhpWorld\Messages\User
     */
    public function getUser()
    {
        return $this->readOneof(1);
    }

    /**
     * Generated from protobuf field <code>.PhpWorld.Messages.User user = 1;</code>
     * @param \PhpWorld\Messages\User $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkMessage($var, \PhpWorld\Messages\User::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getData()
    {
        return $this->whichOneof("data");
    }

}

